[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
authors = [{name = "Freddie Bickford Smith"}]
name = "epig"
dynamic = ["version"]
license = "MIT"
license-files = ["LICENSE.txt"]