# @package _global_

cuda: True

init_length_scale_pdist: False

likelihood_fn: "bernoulli"

model_type: gp

trainer:
  _target_: src.trainers.BernoulliGaussianProcessTrainer
  early_stopping_metric: "val_loss"
  early_stopping_patience: -1
  init_length_scale: 1
  init_output_scale: 10
  learning_rates:
    covar_module.base_kernel.raw_lengthscale: 0
    covar_module.raw_outputscale: 0
    mean_module.raw_constant: 0
  n_optim_steps_min: 0
  n_optim_steps_max: 10_000
  n_samples_test: 5_000
  n_samples_train: 1_000
  n_validations: 100
  optimizer:
    _target_: torch.optim.SGD
    _partial_: True
    lr: 0.005  # 0.01 gives NaN on Two Bells
    momentum: 0.95
  restore_best_model: False
  verbose: False